#!/bin/sh

# Disable kwin compositor - systemd suspend/resume hook
#
# Copyright (c) 2020 Alfonso Brown <alfonsob at acbss.com> and others.
# This software is licensed under the GPL v2 or later.

case $1 in
    pre)  toggle_compositing_in_Kwin.sh ;;
    post) toggle_compositing_in_Kwin.sh ;;
esac
